### ISSUE TITLE
pre-GA: Training / Feedback

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [GoogleCloudPlatform/prometheus-engine#103]
We are immensely interested in making Managed Prometheus run for us. Due to nature of it being pre-GA, does you team offer training for our GCP account? If necessary I can gladly takes this request to our sales representative. Kind regards

**Comment by lyanco** [comment]
At the moment we haven't scaled up training yet - however, it's quite easy to get started yourself, and the support email on the Cloud documentation goes right to us in case you encounter any issues while onboarding. g.co/cloud/managedprometheus

**Comment by eljefedelrodeodeljefe** [comment]
Great. Thanks. Will use that.
