### ISSUE TITLE
Config-reloader Arguments Support

### ISSUE THREAD

**Issue by greskii** [GoogleCloudPlatform/prometheus-engine#1057]
In the example [rule-evaluator.yaml](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/a1ad2b0357cb0dcbdd45d8d4fbc5d8f1a1e6726c/manifests/rule-evaluator.yaml#L119) the container image being referenced for the config-reloader is `gke.gcr.io/prometheus-engine/config-reloader:v0.9.0-gke.1`.  
This version of the config-reloader doe not appear to support the `config-dir` or `config-dir-output` arguments that are defined in the [args](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/a1ad2b0357cb0dcbdd45d8d4fbc5d8f1a1e6726c/manifests/rule-evaluator.yaml#L120).  
Using the unsupported arguments returns the following error:
```
Defaulted container "config-reloader" out of: config-reloader, evaluator, config-init (init)
flag provided but not defined: -config-dir
Usage of /bin/config-reloader:
  -config-file string
    	config file to watch for changes
  -config-file-output string
    	config file to write with interpolated environment variables
  -listen-address string
    	address on which to expose metrics (default ":19091")
  -ready-url string
    	ready endpoint returns a 200 when ready to serve traffic (default "http://127.0.0.1:19090/-/ready")
  -reload-url string
    	reload endpoint triggers a reload of the configuration file (default "http://127.0.0.1:19090/-/reload")
  -watched-dir value
    	directory to watch for file changes (for rule and secret files, may be repeated)
```
From my testing, I was unable to find a tagged releases of the config-reloader in the [artifact registry](https://console.cloud.google.com/gcr/images/gke-release/us/prometheus-engine/config-reloader) that support the `config-dir` and `config-dir-output` arguments.
I found that the [most recently published](https://console.cloud.google.com/gcr/images/gke-release/us/prometheus-engine/config-reloader@sha256:21055a361185da47fbd2c21389fb5cd00b54bfed5c784e0dc258b5b416beaf7e/details) release (not tagged) of the config-reloader container image **does** support the `config-dir` and `config-dir-output` arguments.  
It would be great to see a new tagged release of the config-reloader with support for the `config-dir` and `config-dir-output` arguments.
Thank you!

**Comment by maxamins** [comment]
@greskii Thanks for brining this to our attention. We plan on doing a new release soon, which will resolve this issue. In the meantime, you can use `us.gcr.io/gke-release/prometheus-engine/config-reloader@sha256:21055a361185da47fbd2c21389fb5cd00b54bfed5c784e0dc258b5b416beaf7e`. I confirmed that it supports the `config-dir` & `config-dir-output` arguments.

**Comment by greskii** [comment]
Thanks for the response.  As this was just an "FYI", I'll close the issue.
