### ISSUE TITLE
Release tags for docker images

### ISSUE THREAD

**Issue by ksoftirqd** [GoogleCloudPlatform/prometheus-engine#1081]
Hi,

Manifests in the latest release branch (`v0.12.0`) don't use image tags with docker images and the corresponding tags are missing in the docker registry (the latest one available is `v0.11.0-gke.3`, it seems).

It would be great to tag the corresponding images with `v0.12.0` -- this would considerably simplify the upgrade process.

Thank you

**Comment by bernot-dev** [comment]
Thank you for this feedback. We are aware of this issue and looking into options to create the tags.

**Comment by pintohutch** [comment]
Hey @ksoftirqd - we have fixed our image tagging issue and are beginning to re-populate our manifests with the tags.

I supplemented the `v0.12.0` release tag with https://github.com/GoogleCloudPlatform/prometheus-engine/releases/tag/v0.12.0-imgtag that uses the tagged images in the install manifests.

Closing the issue.
