### ISSUE TITLE
Looks like export.debug.batch-size doesn't have an effect

### ISSUE THREAD

**Issue by kacpercesarz98** [GoogleCloudPlatform/prometheus-engine#1128]
Hello I need to decrease usage of System limit "Service time series ingestion requests per minute" in GCP. To do that I wanted to increase batch-size but it looks like this parameter doesn't change anything. I added bellow extra argument but GCP metrics and logs do not show any change in behaviour.

```
  - name: export.debug.batch-size
    value: '200'
```

<br class="Apple-interchange-newline">

**Comment by pintohutch** [comment]
Hey @kacpercesarz98,

That configuration is specifically setting the number of `TimeSeries` objects in a given [`timeSeries.create`](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/create) request, which is what the GMP collectors use to send custom metrics to Cloud Monitoring.

The "Service time series ingestion requests per minute" issue is actually not relevant to the GMP collectors, but rather the system metrics used in your GCP project.

To inquire about raising this, I would file a support ticket with GCP.

Hope that helps.
