### ISSUE TITLE
GMP frontend becomes unresponsive ~once/week, probable memory leak?

### ISSUE THREAD

**Issue by yasha-spare** [GoogleCloudPlatform/prometheus-engine#1157]
I think GMP frontend has a memory leak?  Our GMP frontend pods become unresponsive about once per week, get connection errors/timeouts trying to call them.  Is fixed by us restarting the pods.  And also memory just rises steadily, and when we restart the pods, it drops:

![image](https://github.com/user-attachments/assets/19ac1acd-05cd-4819-9452-a05df0599451)

**Comment by dashpole** [comment]
Thanks for the report!  We are probably going to need a profile to figure out what the leak is. @pintohutch are there any other debugging steps we should take first

**Comment by lyanco** [comment]
FWIW the frontend container is no longer recommended; we recommend using the [datasource syncer](https://cloud.google.com/stackdriver/docs/managed-prometheus/query#grafana-oauth) method instead to authenticate to Grafana.

**Comment by pintohutch** [comment]
Thanks for reporting @yasha-spare. This is good to know.

For now, we are recommending people use the datasource-syncer, per the comment above.

**Comment by yasha-spare** [comment]
Sounds good, will look into this, ty all!
