### ISSUE TITLE
Self-deployed collection example manifest image tags for v0.13.1

### ISSUE THREAD

**Issue by mhoran** [GoogleCloudPlatform/prometheus-engine#1163]
The image tags for the example prometheus.yaml went backwards with the release of v0.13.1. See https://github.com/GoogleCloudPlatform/prometheus-engine/blame/v0.13.1/examples/prometheus.yaml#L111 vs https://github.com/GoogleCloudPlatform/prometheus-engine/blame/v0.13.0/examples/prometheus.yaml#L111 (same for config-reloader).

**Comment by pintohutch** [comment]
Ah thanks @mhoran - that was an oversight. Lemme patch that.

**Comment by pintohutch** [comment]
Ok - I tagged a fix: https://github.com/GoogleCloudPlatform/prometheus-engine/releases/tag/v0.13.1-imgtag

Let us know if there are any other issues
