### ISSUE TITLE
`nomos vet` doesn't like the crd definitions in manifests/setup.yaml

### ISSUE THREAD

**Issue by nresare** [GoogleCloudPlatform/prometheus-engine#141]
Running `nomos vet --no-api-server-check` on a configsync repository where `manifestes/setup.yaml` is copied to the `cluster` directory fails with errors stating a few of the following error:

This is true for the repo as of 98a5c8aaf7972ea8293d01d6a1cebc95b0e53ad5 as well as version v0.2.3 

```
[6] KNV1045: Configs with "status" specified are not allowed. To fix, either remove the config or remove the "status" field in the config:

source: /Users/noa/fun/prometheus-engine/tmp/cluster/setup.yaml
metadata.name: podmonitorings.monitoring.googleapis.com
group: apiextensions.k8s.io
version: v1
kind: CustomResourceDefinition

```

My nomos version: 
```sh
$ nomos version |grep CLI   
                                 <nomos CLI>         v1.10.0-rc.8
```

**Comment by nresare** [comment]
https://github.com/GoogleCloudPlatform/prometheus-engine/pull/142

**Comment by fabxc** [comment]
The status section of our CRDs is crucial to provide feedback on whether the requested spec/config could be applied successfully. We're not using it to the full extent at this point but definitely will.

What's this `nomos` tool and do you have any background on why it complains about it?
Status sections are part of almost all core Kubernetes resources so it's curious why something would complain about them for custom resources.

**Comment by nresare** [comment]
Removing the status section from the CRD objects' yaml representation will not remove them from their corresponding Kubernetes objects. One can run `kubectl apply` providing a kubernetes object yaml representation without the status section, and the status section will still be included reading back the object using for example `kubectl get -o yaml`.

`nomos` is a tool that is part of the [Anthos Config Sync](https://cloud.google.com/anthos-config-management/docs/how-to/nomos-command) product available as part of the GCP platform. It provides a mechanism for creating and maintaining a set of kubernetes objects that are kept in sync with a set of yaml files checked into a git repository in a certain structure. Managed objects will be created and if they objects on the k8s cluster diverge from the their yaml representation (by either the objects or the yaml files changing) there is a reconciliation process that will attempt to crate/update/delete the kubernetes objects to match their yaml counterparts.

In this context, having a status section in the yaml representation that one attempts to reconcile into the cluster does not make conceptual sense, as the status section is a way for the cluster to signal the status of the object. Consequently, Config Sync will refuse to deal with yaml representations of objects that has a status object, and the `nomos vet` tool reflects this design decision.

**Comment by fabxc** [comment]
Thanks for all the context. I initially misunderstood and thought this was about removing the OpenAPIV3 definition for status info provided by the CR, not the status of the CRD itself. Merged the respective PR. Thank you for bringing this up.
