### ISSUE TITLE
Error querying Prometheus instance

### ISSUE THREAD

**Issue by fkollmann** [GoogleCloudPlatform/prometheus-engine#143]
Hi, the rule-evaluator gives the following error:

```
caller=main.go:324 msg="Error querying Prometheus instance" err="execute query: Error querying Prometheus: client_error: client error: 403"
```

I guess there is some GCP permission missing on the GKE cluster service account?

Best Regards, Felix

**Comment by fabxc** [comment]
If you are not configuring explicit credentials the node default service account is used.
For the rule-evaluator that need `monitoring.timeSeries.create` and `monitoring.timeSeries.read` permissions.

**Comment by fkollmann** [comment]
I created a new role and assigned it to the GKE service account which solved the issue:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/106287/154652550-b7b97953-cd79-4633-bfdc-1ca5a1e48ca6.png">
