### ISSUE TITLE
v0.3.0 manifests/operator.yaml referencing docker image not yet uploaded

### ISSUE THREAD

**Issue by nresare** [GoogleCloudPlatform/prometheus-engine#146]
As of now (2022-02-18 12.33 UTC) the image reference in the gmp-operator Deployment in manifests/operator.yaml mentions  `gke.gcr.io/prometheus-engine/operator:v0.3.0-gke.0` which is a release that does not seem to be uploaded to the right location. 

While I understand that it is a bit tricky to have a solid method of tagging a version that contains references to built artefacts of that same version, it would be nice if newly released versions referenced docker images that exists at least pretty quickly after the release.

**Comment by andysim3d** [comment]
Hi @nresare , image `gke.gcr.io/prometheus-engine/operator:v0.3.0-gke.0` is published. you can find it in https://pantheon.corp.google.com/gcr/images/gke-release/global/prometheus-engine/operator

**Comment by Jonpez2** [comment]
Is this still the case, please?  How can your clients know when your release is fully baked?  We have automated processes to update our external dependencies, so we need something a bit more formal please!

Note btw that that pantheon.corp link doesn't work in the outside world.

Thanks!

**Comment by pintohutch** [comment]
Hi @Jonpez2 - we have indeed remedied this delay now, such that any tag of the form `vX.Y.Z` should have the images readily available in the manifests.

Note: this is _not_ the case for any tags of the form `vX.Y.Z-rc.K`.

**Comment by Jonpez2** [comment]
Wonderful.  Thank you!
