### ISSUE TITLE
Bug: config-reloader fails when posting to the /-/reload endpoint

### ISSUE THREAD

**Issue by djfinnoy** [GoogleCloudPlatform/prometheus-engine#147]
While debugging some issues we discovered the following errors  in the `config-reloader` containers from the `collector` daemonset.
```
level=error 
ts=2022-02-24T14:09:50.588593579Z 
caller=runutil.go:99 
msg="function failed. Retrying in next tick" 
err="trigger reload: reload request failed: Post \"http://localhost:19090/-/reload\": dial tcp [::1]:19090: connect: connection refused"
```

The problem is located in the `daemonset`:
```
# k edit daemonset collector -n gmp-system

...
      - args:
        - --config-file=/prometheus/config/config.yaml
        - --config-file-output=/prometheus/config_out/config.yaml
        - --reload-url=http://localhost:19090/-/reload      <--- THIS SHOULD BE PORT 19091
        - --listen-address=:19091
```

It briefly works when correcting the port, but then I think the operator overrides my edit and goes back to the broken config.

**Comment by fabxc** [comment]
The port should be correct with `19090`. The reloader triggers a reload in the `prometheus` container when it observes a configuration change. The `19091` is just the port the config reloader reports metrics about itself on.

How often and when do you see the initial error? It could certainly happen when the config reloader container starts before the Prometheus container. Then attempting to trigger a reload would log the error.
That would not matter however as Prometheus would read the most recent config file on startup anyway.

If you observe the error after both containers have started successfully, that could indeed be a problem.

**Comment by djfinnoy** [comment]
Ah, I didn't see any errors after modifying the port, so I wrongly assumed that my edit did something useful.

It's now clear that the error tends to occur right after a pod has started: it's probably just a race-condition thing.
