### ISSUE TITLE
GKE autopilot support

### ISSUE THREAD

**Issue by raphaelauv** [GoogleCloudPlatform/prometheus-engine#148]
Currently I can't activate Google Cloud Managed Service for Prometheus for my GKE autopilot 

`Managed Prometheus is not supported for Autopilot clusters. `

Release channel : Rapid channel
Version : 1.21.5-gke.1302

Thanks

**Comment by fabxc** [comment]
Currently installation via `gcloud` is not supported on autopilot.
However, you can self-install managed collection to Autopilot clusters without issues via the respective manifests. You need to add the flag `--host-network=false` [here](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/main/manifests/operator.yaml#L168) however. We may offer separate manifests in the future to avoid this manual change.

**Comment by raphaelauv** [comment]
@fabxc talk about this line https://github.com/GoogleCloudPlatform/prometheus-engine/blob/511d31f6d53c8c7b117873614b71dfd199942d83/manifests/operator.yaml#L168

( his link is not a permanent link )

**Comment by raphaelauv** [comment]
@fabxc 

When I try to install with 

`--host-network=false`

I have this error -> https://github.com/GoogleCloudPlatform/prometheus-engine/issues/186

**Comment by pintohutch** [comment]
There was a similar issue at GoogleCloudPlatform/prometheus-engine#178.

Could you try the instructions from the [last comment](https://github.com/GoogleCloudPlatform/prometheus-engine/issues/178#issuecomment-1092825472) to see if that helps?

**Comment by iamolegga** [comment]
Are there any plans for autopilot support in Managed Service for Prometheus? If so what's the ETA? I have to decide if it worth to wait for it or go with a self-deployed collection

**Comment by lyanco** [comment]
Looking like close to the end of the month, if all goes well. Might bleed a bit over.

**Comment by lyanco** [comment]
We're code complete. Need to roll out 0.4.3 (likely next week) then we can enable on Autopilot. I'll have a better estimate for you once that process starts, but it seems quite soon.

**Comment by JishnuM** [comment]
@lyanco hi - any update on this? I see that 0.4.3 is [rolled out](https://github.com/GoogleCloudPlatform/prometheus-engine/releases/tag/v0.4.3-gke.0), however we still cannot enable Managed Prometheus on Autopilot

**Comment by lyanco** [comment]
Hey Jishnu,

AP support is making it into the release pipeline this week, so I'd expect it to be available within 1-2 weeks from now! Been a journey...

**Comment by JishnuM** [comment]
Awesome news, congratulations on the launch and looking forward to it!

**Comment by pintohutch** [comment]
I'm going to close this as the canonical issue is being tracked at #300.

Please tune in there for updates!
