### ISSUE TITLE
Error with webhook when deploying to GKE

### ISSUE THREAD

**Issue by jaevans** [GoogleCloudPlatform/prometheus-engine#151]
I'm attempting to deploy a managed collector using the directions from [Get started with managed collection](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed) on GKE (standard). I can deploy the operator using kubectl without any issue, but any time I try to create a PodMonitoring resource, I get 
`Internal error occurred: failed calling webhook "default.podmonitorings.gmp-operator.gmp-system.monitoring.googleapis.com": Post "https://gmp-operator.gmp-system.svc:8443/default/monitoring.googleapis.com/v1alpha1/podmonitorings?timeout=10s": context deadline exceeded`

If I port-forward to  the `gmp-operator` service on 8443 and attempt to post data, I get a successful result.

```json
{
  "kind": "AdmissionReview",
  "apiVersion": "admission.k8s.io/v1",
  "response": {
    "uid": "705ab4f5-6393-11e8-b7cc-42010a800002",
    "allowed": true,
    "status": {
      "metadata": {},
      "code": 200
    },
    "patch": "W3sib3AiOiJhZGQiLCJwYXRoIjoiL21ldGFkYXRhL2NyZWF0aW9uVGltZXN0YW1wIiwidmFsdWUiOm51bGx9LHsib3AiOiJhZGQiLCJwYXRoIjoiL3NwZWMvdGFyZ2V0TGFiZWxzIiwidmFsdWUiOnsibWV0YWRhdGEiOlsicG9kIiwiY29udGFpbmVyIl19fSx7Im9wIjoiYWRkIiwicGF0aCI6Ii9zdGF0dXMiLCJ2YWx1ZSI6eyJvYnNlcnZlZEdlbmVyYXRpb24iOjB9fV0=",
    "patchType": "JSONPatch"
  }
}
```

Webhooks are one of the things I don't seem to be able to get my head around, so I'm not sure where to go from here. The deployment was literally copy/paste from the web page into my existing cluster.

**Comment by fabxc** [comment]
Thanks for already verifying the the operator appears to work as intended. 
The error implies that the Kubernetes API server timed out when trying to contact the operator on the webhook endpoint, which certainly seems odd given the operator is available in your manual test. Is the operator deployed in the `gmp-system` namespace?

**Comment by jaevans** [comment]
Yes, the deployment is in the `gmp-system` namespace. I also tested in a pod and it worked. This is leading me to think there's a firewall issue between the control plane and the service. I tried changing `8443` to `443` everywhere in the operator config, but that didn't fix it.

This is a "protected" GKE cluster

**Comment by jaevans** [comment]
Leaving the port at 8443 and adding a firewall rule between the control plane and the cluster allows the webhook to succeed. It would be best if we didn't have to do this, but at the very least noting it in the documentation would be good.

**Comment by lyanco** [comment]
I've added this to our new troubleshooting page: https://cloud.google.com/stackdriver/docs/managed-prometheus/troubleshooting#control-plane-firewall

Thanks for bringing this to our attention!
