### ISSUE TITLE
Metrics aggregation across multiple projects

### ISSUE THREAD

**Issue by areyia** [GoogleCloudPlatform/prometheus-engine#159]
Similar to https://github.com/GoogleCloudPlatform/prometheus-engine/issues/154, 
Having the issue where we want one of our projects to be the master project and gather metrics from all other projects. 
We have managed collection running in all projects and would like all metrics to be available in this master project. I understand that at this point, all I need to do is add all the projects to the metrics scope of the master project.

The [documentation](https://cloud.google.com/monitoring/settings?hl=en) tells us how to do it via the UI and API, and I have verified that they both work. However, it would be preferable if we could do this via configuration - is this supported and are there any docs on it?

**Comment by lyanco** [comment]
We do not have a way to configure metrics scopes via YAML. It's not a Prometheus-native concept (it's a Cloud Monitoring concept).

You can configure scopes and monitored projects via Terraform, however: https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/monitoring_monitored_project

**Comment by areyia** [comment]
I see, thanks for the quick revert, that was what I found too. It seems like Terraform or using the API would be the best way forward then. Thanks for confirming!
