### ISSUE TITLE
arm64 images

### ISSUE THREAD

**Issue by superbrothers** [GoogleCloudPlatform/prometheus-engine#166]
I uses GMP from my home raspi cluster, but I build them myself as no arm64 image is provided. please consider providing arm64 images.

**Comment by pintohutch** [comment]
Hi @superbrothers thanks for mentioning (and sharing) arm64 images!

We actually have support for building them yourself using Google Cloud Build from #346.

You should be able to build any image yourself using our make target, e.g.
```bash
% CLOUD_BUILD=1 make frontend
```

This isn't including the Prometheus fork.

Stay tuned for official support for that as well as the other binaries here. Keeping this open to track that effort.

**Comment by pintohutch** [comment]
Whoop - we have support for ARM images as of https://github.com/GoogleCloudPlatform/prometheus-engine/releases/tag/v0.7.0. Closing.
