### ISSUE TITLE
PromQL delta() function `unexpected error: runtime error: divide by zero`

### ISSUE THREAD

**Issue by willchan** [GoogleCloudPlatform/prometheus-engine#172]
I have a simple query: `delta(my_metric[1h:])` which returns `unexpected error: runtime error: divide by zero` when entered into the Cloud Console Managed Service for Prometheus page.

**Comment by pintohutch** [comment]
Hello,

We recently rolled out some changes to alleviate this. Can you confirm if this is still happening for you?

**Comment by willchan** [comment]
Works now! Thanks.
