### ISSUE TITLE
Add support for collector to be able to run on nodes with taints

### ISSUE THREAD

**Issue by stephenwilliams** [GoogleCloudPlatform/prometheus-engine#177]
Can support be added so that the collector can run even on nodes with [taints](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) set.

This would be useful because I have a workload that runs on a node-pool that has taints on it, but I want to be able to collect metrics from the pods running on it.

Let me know if there is something that I am missing that would currently allow this.

**Comment by pintohutch** [comment]
Hello,

This should be possible already with the [current tolerations](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/91d173174e102bb55405c9d486afc19be45eb3dd/pkg/operator/collection.go#L277-L281) to the collector daemonset. Is this not working for you?
