### ISSUE TITLE
Context deadline exceeded when deploying a PodMonitoring resource

### ISSUE THREAD

**Issue by Aiesnow** [GoogleCloudPlatform/prometheus-engine#178]
Hello,

First of all I'm sorry if this issue does not fit here, but since the Google Managed Prometheus is fairly new, I'm having a hard time finding some help.

I tried GMP on a dev cluster 2 weeks ago and everything was working like a charm, however since a few days ago I'm not able to deploy a PodMonitoring resource on the cluster due to the following error : 
`Error from server (InternalError): error when creating "monitoring_dev.yaml": Internal error occurred: failed calling webhook "default.podmonitorings.gmp-operator.gmp-system.monitoring.googleapis.com": Post "https://gmp-operator.gmp-system.svc:8443/default/monitoring.googleapis.com/v1alpha1/podmonitorings?timeout=10s": context deadline exceeded`

The same error shows up when I try to deploy the PodMonitoring example from the [documentation](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#gmp-pod-monitoring) : 
`kubectl -n gmp-test apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/prometheus-engine/v0.3.1/examples/pod-monitoring.yaml`

According to the [troubleshooting page](https://cloud.google.com/stackdriver/docs/managed-prometheus/troubleshooting#control-plane-firewall), context deadline errors are due to a firewall problem but we did not change anything related to our network configuration in the past 2 weeks and it was working before.

Thanks in advance for you help,
Aiesnow

**Comment by fabxc** [comment]
It could either be that you've trouble communicating with the API server. But that's unlikely to be the case if other resources work fine.
The other option is that the API server has trouble talking to the GMP operator to run validation on the resources.

Could you see whether the operator pod in the `gmp-system` namespace is running and has no suspicious error logs?

**Comment by Aiesnow** [comment]
The gmp-operator only logs on Pod startup, and it does not show any warning/error log

**Comment by fabxc** [comment]
Can you port-forward to the operator service

```
kubectl -n gmp-system port-forward svc/gmp-operator 8443```
```

And then try querying it from a different shell:

```
curl --insecure https://localhost:8443/default/monitoring.googleapis.com/v1alpha1/podmonitorings
{"response":{"uid":"","allowed":false,"status":{"metadata":{},"message":"contentType=, expected application/json","code":400}}}
```

Output should look something like this. If that works it would indiciate some communication issue between API server and operator.

**Comment by pintohutch** [comment]
Are you running on GKE? If so, I'm curious if you enabled managed collection through [`gcloud`](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#gcloud-cli) or through [`kubectl`](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#kubectl-cli).

**Comment by Aiesnow** [comment]
We enabled it manually from the GCP UI, so I guess it is the same as gcloud

**Comment by pintohutch** [comment]
Gotcha - were you able to find the source of the issue?

If not, could you run this to see what GMP component version you're on?
```
kubectl get deploy gmp-operator -ngmp-system -ojsonpath="{.spec.template.metadata.annotations['components\.gke\.io/component-version']}"
```

**Comment by Aiesnow** [comment]
It shows 0.2.6, since it's out of date, it might be the problem right ?

**Comment by pintohutch** [comment]
Hrm - 0.2.6 should be ok, even though it's not the latest. Could you double-check your firewall rules for the cluster and ensure the control plane can access services in the cluster on port 8443?

**Comment by Aiesnow** [comment]
Thanks a lot ! I managed to create the missing firewall rule (I first tried adding port 8443 on the default "master" rules, then read it was a bad idea to edit these rules so I made a new one). I still have no idea how it did work back when I enabled the option though.

In case someone else faces the same issue, here is how I did (on GCP UI) :

1. Under VPC network -> Firewall, Create a new rule
2.  Choose the same network as the k8s cluster, keep checked "ingress" and "allow"
3. As target : specified service account, then use the service account used for the cluster ( `gcloud container clusters describe` )
4. As source filter, choose IPv4, then use the `masterIpv4CidrBlock` value  ( from `gcloud container clusters describe` )
5. Finally, for ports and protocols, check TCP and input port 8443 (which is the port exposed by the gmp-operator service)

Thanks again for the support !

**Comment by pintohutch** [comment]
Thanks for the detailed report! We'll investigate any potential changes around then and update here with findings.

**Comment by bogdan-dumitrescu** [comment]
I'm seeing something similar when trying to update the PodMonitoring resources in our GKE cluster. The result of this command:

> kubectl get deploy gmp-operator -ngmp-system -ojsonpath="{.spec.template.metadata.annotations['components\.gke\.io/component-version']}"

is `0.2.9`

When trying to run:

`kubectl apply -f pod-monitoring.yaml`, 

I get the following error message:

> Error from server (InternalError): error when creating "test.yaml": Internal error occurred: failed calling webhook "default.podmonitorings.gmp-operator.gmp-system.monitoring.googleapis.com": failed to call webhook: Post "https://gmp-operator.gmp-system.svc:443/default/monitoring.googleapis.com/v1/podmonitorings?timeout=10s": no service port 443 found for service "gmp-operator"

Note the port in the error message - it's looking for the `gmp-operator` service running on port `443`. Which is really strange, because the `gmp-operator` exposes port `8443`. 

If I manually change the `gmp-operator` service to listen to port 443, then the above command to create the PodMonitoring resource works. 

We also haven't changed anything in our network configuration & we already had the 8443 firewall rule added to our network configuration. We successfully created PodMonitoring objects in our cluster on ~10th of May.

**Comment by maguro** [comment]
@pintohutch , which of the above two tickets do we track the progress on this issue?  Also, both seem to be oriented on Autopilot, which I am not using when I encounter this issue.

**Comment by rojomisin** [comment]
I'm just trying to use the example app after enabling GMP on a GKE cluster and it's failing

```
% k apply -f pod-monitoring.yaml 
Error from server (InternalError): error when creating "pod-monitoring.yaml": Internal error occurred: failed calling webhook "default.podmonitorings.gmp-operator.gke-gmp-system.monitoring.googleapis.com": failed to call webhook: Post "https://gmp-operator.gke-gmp-system.svc:443/default/monitoring.googleapis.com/v1/podmonitorings?timeout=10s": x509: certificate is valid for gmp-operator, gmp-operator.gmp-system, gmp-operator.gmp-system.svc, not gmp-operator.gke-gmp-system.svc
```

```
% kubectl -n gke-gmp-system port-forward svc/gmp-operator 8443 
error: Pod 'gmp-operator-647b69cbdd-vdkt5' does not have a named port 'webhook'
```
