### ISSUE TITLE
[BUG] install manifest with HELM , order break

### ISSUE THREAD

**Issue by raphaelauv** [GoogleCloudPlatform/prometheus-engine#185]
when I try to install the manifest in my GKE autopilot 

using helm

I have this error 

```log
unable to recognize "": no matches for kind "OperatorConfig" in version "monitoring.googleapis.com/v1alpha1"
```

![Screenshot from 2022-04-07 16-16-23](https://user-images.githubusercontent.com/10202690/162220332-a08e3147-a33a-41cc-9519-078808c615e4.png)

**Comment by pintohutch** [comment]
Did you apply `manifests/setup.yaml` first, per https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#kubectl-cli?

**Comment by pintohutch** [comment]
FYI we don't maintain an official `helm` chart here and make no guarantees about its functionality. We encourage users to leverage their own helm charts in ways that best suit their needs.

For more context, see https://github.com/GoogleCloudPlatform/prometheus-engine/pull/105#issuecomment-1087862749.

**Comment by raphaelauv** [comment]
thanks
