### ISSUE TITLE
`rate()` incompatibility with Prometheus

### ISSUE THREAD

**Issue by willchan** [GoogleCloudPlatform/prometheus-engine#189]
We have a grafana dashboard measuring rate on a metric. With Prometheus, it works, but with Google Managed Prometheus we get `rate() can only be used with counter series, got GAUGE`.

Reading the [prometheus docs for the rate() function](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate), it notes "`rate` should only be used with counters. It is best suited for alerting, and for graphing of slow-moving counters." But in practice, it allows gauges.

Our application is a metric exporter. It is querying another application and reporting the metrics. That backend application increments values like a counter. But, since it can restart, thus resetting the counter, our exporter application uses a prometheus GAUGE to set the prometheus metric to match the values from the backend application.

This functionality works for Prometheus, but not Google Managed Prometheus.

**Comment by lyanco** [comment]
Our backend system (Monarch) is strongly typed, while Prometheus is not. We send in `TYPE` information on time series as our system requires it. In practice this leads to situations exactly like you discovered, where the loosely-typed Prometheus will cast gauges as counters and run `rate`s, even though you shouldn't be able to do so.

It sounds like you're converting this metric to a gauge unnecessarily. Prometheus counters handle these resets correctly without any user intervention, and you shouldn't need to convert them to gauges (Basically Prometheus treats `counter` value drops as a reset and `rate` functions will implicitly add the fresher, lower value to the previous value to create a standard increasing counter time series when you run the query).

Can you try this and make sure it works? The other thing you can do is send it to us without a TYPE, but when you do that we actually store it both as a counter and a gauge, costing you 2x in ingested samples but it'll work.

Closing this as we can't un-type our system to support this.

**Comment by willchan** [comment]
It makes sense that you are limited since it's probably unreasonable to loosen Monarch's typing in this situation. And I see what you are saying about converting the metric to a gauge unnecessarily. That's true in an abstract sense, but the Golang library makes it difficult for us. As you can see in https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#Counter, the interface does not support a Set(). We only get that with a gauge type. So I see your point that from a wire format standpoint, we should just let the metric value reset, tagged as a counter `TYPE`, and let `rate()` handle it at query time. But with the current Go library, we cannot do that.

That said, this is probably an edge case and I suspect I can find a way to hack around this.

**Comment by lyanco** [comment]
Ack - thanks for the context. An easy hack would be to remove the TYPE field at the source, but you'd be paying twice in that case (once to ingest metric as a gauge, once to ingest as a counter). May be just fine if the volume is relatively low.
