### ISSUE TITLE
Allow disabling rule-evaluator

### ISSUE THREAD

**Issue by willchan** [GoogleCloudPlatform/prometheus-engine#193]
When the [operator is deployed per instructions](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#config-mgd-collection), it sets up both the collector and the rules evaluator. I'd like to only run rule evaluation in some of my clusters (currently, only one).

The [documentation](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#explicit-credentials) provided show how to set up credentials for managed collection, but when following these instructions, the rule-evaluator never gets credentials and crash loops. Even when a GCP service account is set, it fails the readiness probe unless the GCP service account has `roles/monitoring.viewer`, which I actually don't want to give the cluster. I just want to let it collect metrics.

This is a minor issue, but we have monitoring rules set up to detect crash looping and unavailable pods, which is normally indicative of a real issue. I can exclude rule-evaluator from these rules, but I'd much rather be able to disable rule-evaluator from being created by the operator. No sense in wasting resources just to have a dummy pod that no-ops.

**Comment by pintohutch** [comment]
Hello,

I want to check: is the rule-evaluator process actively crashlooping? Or is it running, but the readiness probe marks the pod as unavailable?

**Comment by willchan** [comment]
I think you're right that the readiness probe marks the pod as unavailable. I don't think the rule-evaluator actually crashes itself, but I think the perceived symptom from monitoring is crashing, because I think the kubelet sends a SIGKILL if the readiness probe fails too many times. And the pod terminates with a non-zero exit status, which sets the termination status to Error. We monitor the # of container restarts with termination status == Error, so this sets off our alerts.

**Comment by pintohutch** [comment]
Got it - makes sense. Thanks.
