### ISSUE TITLE
Support querying cAdvisor in kubelet

### ISSUE THREAD

**Issue by willchan** [GoogleCloudPlatform/prometheus-engine#197]
I'd like to configure scraping of the cAdvisor metrics endpoint in the kubelet: https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#metrics-in-kubernetes. The prometheus docs have an example of how to do this: https://github.com/prometheus/prometheus/blob/ec3d02019e84d9d793d2e137891dd7ea6d19ea60/documentation/examples/prometheus-kubernetes.yml#L110. Per the doc, the scraping requires configuring the CA certificate and authorization via the service account token. AFAICT, PodMonitoring doesn't support either of these in its [ScrapeEndpoint](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.3.1/doc/api.md#scrapeendpoint).

**Comment by pintohutch** [comment]
Hello,

We recently added support for cAdvisor scraping in GoogleCloudPlatform/prometheus-engine#203, which made it into our `0.4.0` release. Closing this issue.

**Comment by pintohutch** [comment]
See https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.4.0/doc/api.md#kubeletscraping for specific usage.

**Comment by willchan** [comment]
I tried using this feature but I don't seem to get any cadvisor metrics. I'm not sure if I'm doing something wrong. Is there a way to debug?

**Comment by pintohutch** [comment]
Adding something like the following to your OperatorConfig. I just tried this myself manually and am seeing cadvisor/kubelet metrics being scraped.
```
collection:
  kubeletScraping:
    interval: 30s
```

Are you doing something like this?

**Comment by willchan** [comment]
I believe so. This is what my OperatorConfig looks like in my kubespray managed single node k8s cluster running 1.21. I'm running the 0.4.0 GMP manifests for managed collection in this cluster.

```
$ kubectl -n gmp-public get operatorconfig -o yaml
apiVersion: v1
items:
- apiVersion: monitoring.googleapis.com/v1
  collection:
    credentials:
      key: key.json
      name: cluster-gcp-service-account
    kubeletScraping:
      interval: 5m
  kind: OperatorConfig
  metadata:
    creationTimestamp: "2022-03-11T01:43:01Z"
    generation: 4
    labels:
      kustomize.toolkit.fluxcd.io/name: infrastructure
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: config
    namespace: gmp-public
    resourceVersion: "27453005"
    uid: 2166927b-630f-45b1-b18a-83fb8c40fff1
  rules:
    credentials:
      key: key.json
      name: cluster-gcp-service-account
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by pintohutch** [comment]
Ok here are a few things to check:
1. Ensure the scrape config was generated:
```
kubectl get cm -ngmp-system collector -oyaml
```
You should see entries for `job_name: kubelet/cadvisor` and `job_name: kubelet/metrics`.

2. Check the `/api/v1/targets` page of a collector:
```
kubectl port-forward -ngmp-system <a-collector-pod> 19090
```
Then by going to `http://localhost:19090/targets` in your browser, you should see the kubelet/cadvisor targets there, e.g.:
![kubelet-targets](https://user-images.githubusercontent.com/3731548/167680517-7701bc78-6003-4ba0-8744-3a6f76beb738.png)

**Comment by willchan** [comment]
That was helpful, thanks. I am understanding GMP better now, it looks like the collector is just prometheus under the hood. The targets page indeed had the info I needed. The TLS connection failed on certificate verification. It'd be nice if this showed up in the logs, which I think it does in upstream prometheus. Any chance that could get set up?

It looks like the key difference is that in our previous prometheus configuration, we copied blocks from [earlier prometheus kubernetes service discovery examples](https://github.com/prometheus/prometheus/blob/v1.20.1/documentation/examples/prometheus-kubernetes.yml#L123-L129). These use the API server proxy URLs for the nodes. We were able to successfully scrape these from inside the cluster.

The GMP collector seems to scrape the kubelet directly. It looks like we only generated SubjectAltNames for our API server certificate and not for the kubelet, so the TLS connection fails on scrape. It is scraping using the IP address, whereas the CN covers the hostname.

It's a bit annoying, but I guess the right solution is to fix our kubelet certificate, even though the legacy solution with API server proxy URLs worked. I'll add it to the queue of things to get around to.

**Comment by willchan** [comment]
I looked into it a bit more and kubespray does support configuring this, but it's sort of a pain. It's doing self-signed certs, and fixing this would probably require some manual intervention that I'm hesitant to do. Would it be possible to proxy through the API server or disable the certificate verification? It looks like upstream prometheus has options for both.

**Comment by willchan** [comment]
> > That was helpful, thanks. I am understanding GMP better now, it looks like the collector is just prometheus under the hood. The targets page indeed had the info I needed. The TLS connection failed on certificate verification. It'd be nice if this showed up in the logs, which I think it does in upstream prometheus. Any chance that could get set up?
> 
> Yea - we are working on a better target status reporting mechanism for managed collection as this path of debugging is not ideal. Stay tuned.

Excellent

> 
> > Would it be possible to proxy through the API server or disable the certificate verification? It looks like upstream prometheus has options for both.
> 
> Disabling certificate verification (via `insecure_skip_verify`) seems reasonable. Would you mind opening a Github issue so we can track?

Sure thing.

> 
> Also, out of curiosity, could you provide the working scrape config you were using for your kubespray cluster? Omitting any sensitive data of course.

Will send out of band since I suspect you have access to it.
