### ISSUE TITLE
GMP rule evaluation will not update

### ISSUE THREAD

**Issue by willchan** [GoogleCloudPlatform/prometheus-engine#206]
I've been editing a GlobalRule resource to update the alert expression and alert message. The original alert was too noisy, so I was changing the range vector duration to make it less spammy. I've simultaneously updated the alert message. However, I still get alerts with the old message, which makes me think the alert expression is not updated either. I've tried deleting the GlobalRule resource and recreating the GlobalRule. I've tried renaming the GlobalRule too. It doesn't seem to work. Currently, I'm trying to change the alertname to see if that fixes it.

**Comment by lyanco** [comment]
Hey Will, this is a known issue and will be fixed in our upcoming 0.4.0 release, likely ready this upcoming week.
