### ISSUE TITLE
Installing gmp and add prometheus UI without data make it crash

### ISSUE THREAD

**Issue by dheras-lmes** [GoogleCloudPlatform/prometheus-engine#220]
Hello GMP Team.

Following these instructions, frontend doesnt work.

1. kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/prometheus-engine/v0.4.0/manifests/setup.yaml
2. kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/prometheus-engine/v0.4.0/manifests/operator.yaml
3. curl https://raw.githubusercontent.com/GoogleCloudPlatform/prometheus-engine/v0.4.0/examples/frontend.yaml |
sed 's/\$PROJECT_ID/PROJECT_ID/' |
kubectl apply -n gmp-test -f -
4. kubectl -n gmp-test port-forward svc/frontend 9090

(about point 3, obviously using the correc project ID)

The error that chrome debugg shows is that and when you go through the localhost:9090 it blinks from the original web design of frontend to white

![image](https://user-images.githubusercontent.com/53262140/167862441-9a9e57ee-19c0-4594-9d81-462b47ab43e4.png)

As I can figure this error it showed due not data is already set in the pod monitoring or operator config.

My point is if this can be fixed to let show the website instead go blank and show that error.

**Comment by pintohutch** [comment]
Hi @dheras-lmes,

I don't quite follow the issue. Can you elaborate on how to reproduce? And what exactly you're looking at?

**Comment by pintohutch** [comment]
I'm going to close this as not-reproducible for now. Feel free to reopen if there's more data and we can revisit.
