### ISSUE TITLE
v1alpha1 participants not getting release upgrade?

### ISSUE THREAD

**Issue by salineselin** [GoogleCloudPlatform/prometheus-engine#222]
https://github.com/GoogleCloudPlatform/prometheus-engine/releases/tag/v0.4.0

Hi, we started using GKE managed prometheus before v0.4.0 and have yet to get the new version added to the CRD. Should I still be expecting this CRD update operation to be automatic?

**Comment by pintohutch** [comment]
Hello,

I'm not sure I fully understand, but the latest release is backward compatible with `v1alpha1` resources.

**Comment by salineselin** [comment]
I mean `v1` is unavailable in our cluster currently. If I attempt to deploy a `podMonitoring` resource with `v1`, it fails. My understanding based on the release notes is that the deployed CRD would have a `v1` version added sometime last week.

**Comment by pintohutch** [comment]
IIUC you are running managed-collection installed via `gcloud` over `kubectl apply`ing the [manifests](https://github.com/GoogleCloudPlatform/prometheus-engine/tree/v0.4.0/manifests).

If that's the case, apologies for the slow rollout. I would continue to use `v1alpha1` resources for the time being while the rollout converges.

I can follow up here once we've confirmed `v0.4.0` is fully deployed for all clusters.

**Comment by salineselin** [comment]
I got the update! We can close the issue now or later when its fully deployed to all clusters, up to you.
