### ISSUE TITLE
Units for metrics

### ISSUE THREAD

**Issue by tomasherman** [GoogleCloudPlatform/prometheus-engine#232]
Hi, 
maybe i misunderstand the [prometheus docs](https://prometheus.io/docs/practices/naming/), but it seems to me that metric name should also determine its unit (for example xxx_yyy_seconds should determine that the number represented by this metric is in seconds). However, when using managed prometheus, it seems like it's not the case. Is that by design? If not, how should i go about setting metric unit?

Thanks

**Comment by lyanco** [comment]
Could you explain a little more what you're seeing instead of seconds?

In general, Prometheus has no concept of units; you set the y-axis units in Grafana or whatever front end you use instead.
