### ISSUE TITLE
Can I scrape metrics from VMs using GMP?

### ISSUE THREAD

**Issue by jacek-jablonski** [GoogleCloudPlatform/prometheus-engine#239]
Hi,
I couldn't find an answer to my question anywhere in the docs. If I am missing something, please guide me.
Is it possible to scrape metrics from GCE's VMs with GMP?
If yes, where should I start looking?
If no, then what is the preferred way to scrape prometheus metrics exposed in VMs so I can access them in Google Monitoring?
Thanks in advance.

**Comment by xichen2020** [comment]
In theory you should be able to run GMP on GCE as a drop-in replacement for your Prometheus server, although we only tested it in Kubernetes environments.

Assuming you are running in a non-containerized environment, you can run it on GCE following instructions here: https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-unmanaged#gmp-binary 

Wanna give it a try?

**Comment by jacek-jablonski** [comment]
Hi,
Thanks for response. I already did it this morning. I can confirm that GMP Prometheus binary works fine on VM.
Cheers.

**Comment by xichen2020** [comment]
Great to hear! Thanks.

**Comment by jacek-jablonski** [comment]
So to sum up the way is to install GMP Prometheus on VM and not to use Kubernetes Prometheus to monitor VMs. Am I right?

**Comment by xichen2020** [comment]
By "Kubernetes Prometheus" do you mean [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus)? If so, yes kube-prometheus is for Kubernetes environments only. If you are running on GCE, installing GMP on VM is the right way to go.

**Comment by jacek-jablonski** [comment]
Yes. Great. Thanks for claryfying.
