### ISSUE TITLE
Add Grafana supported authentication to Prometheus UI

### ISSUE THREAD

**Issue by iamkarlson** [GoogleCloudPlatform/prometheus-engine#242]
With managed Prometheus, we can use it only with on-premise Grafana where access is ruled out with RBAC. However, if I want to use Grafana Cloud, for example, I cannot stick to Prometheus UI. It doesn't have such a simple thing as authentication. Exposing it openly via public address would cause a security threat to our services. 

It would be great if we can pass some config to specify a basicAuth for example to access this service. Another option can be to use client TLS but it seems significantly more difficult at this moment in time.

**Comment by lyanco** [comment]
Sorry - having trouble understanding your request. Do you mean you want to be able to query GMP from Grafana Cloud, or you want to be able to run interactive queries via the Prometheus UI?

If the former, we would love to add this but it's actually a defect in Grafana. Their Prometheus data source does not allow you to pass in OAuth credentials, which the GCP APIs need to authenticate calls. I'd recommend opening up a ticket with them to add OAuth to the Grafana Prometheus data source.

If the latter, we have an interactive query UI in Cloud Console that can be accessed via regular GCP credentials, and this may solve your problem: http://console.cloud.google.com/monitoring/prometheus

**Comment by iamkarlson** [comment]
I want to be able to query GMP from Grafana Cloud. Sorry, but I think it's a weird accusation to blame Grafana that they don't pass something. On all your promotional materials you're saying that GMP is a drop-in replacement for Prometheus, and this is far from the truth. GMP doesn't have write endpoints and you have to use this hack with auth proxy to make Grafana work. I can figure out some hacks to write metrics, but authentication is the simplest thing you can do for your customers who are using Grafana Cloud. Otherwise, we just have to let it go and use Grafana's Prometheus offering.

**Comment by lyanco** [comment]
Our write instructions are here: https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed and here: https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-unmanaged. Works pretty well.

I'm not sure what to tell you about the OAuth issue. We intentionally made GMP work with the standard Grafana Prometheus datasource to maximize compatibility with what people are doing today. If Grafana doesn't support OAuth for the Prometheus datasource, then we can't pass OAuth creds to our GCP API, meaning those APIs reject you as unauthorized. The proxy is our way to work around this lack of OAuth support. Unfortunately we don't have the ability to like, remove authorization from the GCP APIs. 

You could presumably host the proxy in a GCP project and have your Grafana Cloud data source hooked up to that, and then everything should work as expected. This seems pretty straightforward IMO.

We'd love to get rid of the FE proxy, but until they add OAuth in the Prom datasource, we can't.

**Comment by lyanco** [comment]
OK - so I understand what you're saying a bit better now. Your concern isn't about the proxy itself, more that the proxy doesn't have any auth which would allow outside calls. This makes sense, sorry for misunderstanding.

We can add this. Would basicAuth suffice? What is your prefernece?

**Comment by iamkarlson** [comment]
Yes, basicAuth would be fine because it's supported by Grafana for Prometheus data source. Also, if you would have some long-living tokens - it would be also fine, you can put them in custom headers too.

**Comment by baryal2022** [comment]
This would definitely help! What is the expected timeline?

**Comment by lyanco** [comment]
We're going to start work on this soon. Thanks for poking us.

**Comment by lyanco** [comment]
This is now available as of our 0.5.0 release! https://cloud.google.com/stackdriver/docs/managed-prometheus/query#basic-auth-ui

**Comment by iamkarlson** [comment]
Thank you very much! That's should solve our problem!

**Comment by kgibson-insight** [comment]
can we please have an option to auth with a service account? it's not always feasible to create a project iam user for basic auth.

**Comment by pintohutch** [comment]
Hi @kgibson-insight, can you file a separate issue with a little more detail?
