### ISSUE TITLE
Node exporter - Scraping

### ISSUE THREAD

**Issue by naveensrinivasan** [GoogleCloudPlatform/prometheus-engine#243]
Hi,
     I am trying to run GMP. We are used to NodeExporter, and it would be nice to have that. How can we configure GMP to scrape nodeexporter? 

```
Annotations:  prometheus.io/path: /metrics
              prometheus.io/port: 9100
              prometheus.io/scrape: true
```

![image](https://user-images.githubusercontent.com/172697/172686112-d094c4f6-8411-4d0e-be93-996d5f604675.png)

```
apiVersion: v1
items:
- apiVersion: monitoring.googleapis.com/v1
  kind: PodMonitoring
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.googleapis.com/v1","kind":"PodMonitoring","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"prom-example"},"name":"prom-example","namespace":"gmp-test"},"spec":{"endpoints":[{"interval":"30s","port":"metrics"}],"selector":{"matchLabels":{"app":"prom-example"}}}}
    creationTimestamp: "2022-06-01T18:12:27Z"
    generation: 1
    labels:
      app.kubernetes.io/name: prom-example
    name: prom-example
    namespace: gmp-test
    resourceVersion: "4734651"
    uid: 750188dc-e9a5-4477-8a17-d49dc077da33
  spec:
    endpoints:
    - interval: 30s
      port: metrics
    selector:
      matchLabels:
        app: prom-example
    targetLabels:
      metadata:
      - pod
      - container
  status:
    conditions:
    - lastTransitionTime: "2022-06-01T18:12:27Z"
      lastUpdateTime: "2022-06-01T18:12:27Z"
      status: "True"
      type: ConfigurationCreateSuccess
    observedGeneration: 1
 ```

**Comment by lyanco** [comment]
Hey Naveen,

You'll have to craft a PodMonitoring resource to discover the node-exporter exporters and scrape them. What you pasted above is the example PodMonitoring resource that scrapes the example app.

This reference PodMonitoring will probably work for you: https://github.com/GoogleCloudPlatform/prometheus-engine/blob/29ac8e9175732b1d75b848a8a023c4da2ef5dfa0/cmd/operator/deploy/node-exporter/pod_monitoring.yaml

**Comment by naveensrinivasan** [comment]
Thanks, I was able to deploy the one that you shared. It still doesn't show up. How do I debug this?

**Comment by lyanco** [comment]
So we're developing a targets status page to help you figure out if it's not appearing due to a bad scrape config. Not ready yet.

I'd start debugging by port-forwarding node-exporter and manually verifying that it's accessible as expected. Then once that's done, I'd tweak the PodMonitoring until metrics appear.

**Comment by lyanco** [comment]
You could also keep using your existing Prometheus deployment and scrape configs but switch to GMP via self-deployed collection: https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-unmanaged.

**Comment by lyanco** [comment]
We've developed some copy-pastable YAML that will let you easily scrape node-exporter without having to figure it out yourself: https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters
