### ISSUE TITLE
Scrape Non-GKE Resources Using Fully Managed GMP?

### ISSUE THREAD

**Issue by dave-pollock** [GoogleCloudPlatform/prometheus-engine#253]
I run most of our scrape targets in GKE, however there are some scrape targets running on VMs, which our current Prometheus discovers using DNS service discovery. I'm hoping to migrate to the managed prometheus service, but as far as I can tell the managed version of GMP can only scrape Kubernetes pods.

Am I correct in thinking that as it stands today, I would need to deploy the self-managed version of GMP in order to scrape the VMs?

If so, are there any plans to support DNS service discovery in the fully managed GMP, so that targets outside Kubernetes can be scraped?

Thanks!

**Comment by pintohutch** [comment]
Hi @dave-pollock,

That is correct. We're currently focusing on streamlining the K8s workload experience as much as possible before considering anything else.

If it's helpful, we have [documentation](https://cloud.google.com/stackdriver/docs/managed-prometheus/best-practices/ingest-and-query) on best practices on using GMP in heterogenous environments.

**Comment by dave-pollock** [comment]
Ok no worries, thank you.
