### ISSUE TITLE
GMP frontend permission denied with managed collection

### ISSUE THREAD

**Issue by brokenjacobs** [GoogleCloudPlatform/prometheus-engine#255]
Hello I've added GMP managed collection to my cluster and I am attempting to setup the frontend proxy to use grafana. The frontend is reporting permissions errors when trying to query:
![image](https://user-images.githubusercontent.com/3159463/174123077-22ef89b4-3b82-4d5d-aa26-3fe3a4578419.png)

I can do the curl command in the examples and get up metrics back, and the deployment from github is using the default service account in the gmp-public namespace, where I put the frontend deployment. The default compute SA has editor rights in the project the cluster is in, so I'm confused as to why I am seeing this error. Any advice?

Workload Identity is enabled in this cluster.

**Comment by lyanco** [comment]
Last time we saw this error, it was due to misconfigured or mistyped secrets. Could you follow these troubleshooting instructions and let us know? https://cloud.google.com/stackdriver/docs/managed-prometheus/troubleshooting#secret-typos

**Comment by brokenjacobs** [comment]
I did replace the PROJECT_ID in the sample with the project ID. 

This is a managed instance of GMP using workload identity, there is no secret that I am aware of meeting this description, it's supposed to use the default compute account from my read of the docs? Or am I missing something? I don't want to create a keyfile for this.

**Comment by lyanco** [comment]
The default compute account is only used for non-workload-identity clusters running on GCP. Since you're using WI, you'll have to create/bind/grant permissions to a service account as described here: https://cloud.google.com/stackdriver/docs/managed-prometheus/query#gmp-wli-svcacct

**Comment by brokenjacobs** [comment]
makes sense, thank you. And I assume I need to patch/modify the default manifest to use said service account, like everything else that uses workload identity? Thanks!

I don't know how I missed that in the documentation, but I feel there is a docbug there somewhere.

**Comment by lyanco** [comment]
Honestly I'm not an expert on Workload Identity, though I believe the above instructions should work verbatim if you use the right namespace.

And it's not just you missing it - confusion and trouble with Workload Identity was the largest source of stress early on, and it continues to be a point of confusion. We put it on every page to try and help, but stuff like this still happens. I'll look and see where it can be improved on that page.
