### ISSUE TITLE
Troubleshoot a non working PodMonitoring resource

### ISSUE THREAD

**Issue by Aiesnow** [GoogleCloudPlatform/prometheus-engine#257]
Hello,

I need help to troubleshoot a PodMonitoring that does not scrape any metric from a specific pod.
I deployed 2 PodMonitoring resources on the same cluster, one is working perfectly but the other one does not seem to do anything.

I followed the official troubleshooting guide from the [documentation](https://cloud.google.com/stackdriver/docs/managed-prometheus/troubleshooting#ingest-problems) :

- I used the same selector as the service that exposes the monitored pod
- I tried a named port and a numbered port but it does not change anything (At first the port wasn't defined in containerPorts but adding it did not solve the problem)
- I can access the /metrics endpoint from the pod without any problem using port forwarding
- I deployed the resource in the right namespace
- Everything is deployed on Google Cloud

Additionnaly, I checked the logs from both the operator and the collectors, and I did not see any warning or error related to this pod.

The logs from the monitored pod indicates that the /metrics endpoint is called every 10 seconds so it looks like collectors can access the endpoint, but : 

- The `up` metric for the pod indicates 0
- The `scrape_duration_seconds` metric for the pod indicates 30, which looks like a timeout error.

Is there anything to do have access to more logs ?

Thanks in advance for the help

**Comment by djfinnoy** [comment]
I'm experiencing the same issue. PodMonitoring works for a bunch of our off-the-shelf apps, but it does not work for any of our bespoke apps. Looks like it happened during the transiton from 0.3 to 0.4. Now running 0.4.1. Tried with named and numeric ports.

**Comment by pintohutch** [comment]
Hi,

With managed collection, there's a Prometheus server scraping your workloads on every node in the cluster (pod named `collector-*` in the `gmp-system` namespace). I would find the collector co-located with your workload, e.g.

```bash
# Get the node IP the pod is running on:
kubectl get po -lapp=my-workload -owide
# Find the collector pod on that node:
kubectl describe node <node-ip>
# Get logs of the collector pod:
kubectl logs -ngmp-system collector-abcde
# Another helpful step is to port-forward the UI of that pod and check the /api/v1/targets endpoint:
kubectl port-forward -ngmp-system collector-abcde 19090
```

We're working on making this scrape-diagnosing problem more streamlined in the meantime.

For the port name issue specifically, I'm curious if the endpoint name being 16 characters (over the [15-character limit](https://github.com/kubernetes/enhancements/blob/115721691f7a4c63af0efd52107195241ac5ac0f/keps/sig-network/0752-endpointslices/README.md#endpointslice-api)) is causing any issues.

**Comment by djfinnoy** [comment]
Got it working, turns out that it was netpol after all (it usually is).

It's quite strange though: Turns out that our netpol rules were misconfigured:
```
  # Old config, worked with 0.3.0 but not 0.4.1
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: gmp-system
```
The namespace selector is wrong, there is no `name` label on the `gmp-system` namespace, but `v0.3.0` is still able to reach the pods. Stops working when upgrading to `0.4.0` / `0.4.1`.
When I modify the `netpol` into something correct, it starts working:

```
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gmp-system
```

I saw that there were RBAC changes from 0.3.0 to 0.4.0, perhaps the old version was able to bypass the network policy?

**Comment by pintohutch** [comment]
Ah glad to hear. We did scope down the RBAC permissions with 0.4.x releases, so that may be the case.

@Aiesnow - is this still an outstanding issue? Or can this be closed?
