### ISSUE TITLE
[Feature] Operator to support alert manager

### ISSUE THREAD

**Issue by HaddadJoe** [GoogleCloudPlatform/prometheus-engine#274]
Apologies in advance if this is not the right place to open feature requests, please redirect me to the right place as I did not find any mention to that in the readme.

Is it possible for the Operator to support deployment of prometheus alert manager? This would be much more convenient instead of deploying it as standalone instance. Would you consider PRs open in that direction?

**Comment by lyanco** [comment]
Already in flight! :-)

See https://github.com/GoogleCloudPlatform/prometheus-engine/pull/273

**Comment by HaddadJoe** [comment]
Amazing thanks!
