### ISSUE TITLE
No ui or any visualization for self-deployed rule-evaluator rules

### ISSUE THREAD

**Issue by DavidMij** [GoogleCloudPlatform/prometheus-engine#291]
Hi all,
i'm using self-deploy rule evaluator on my GKE cluster, how can i see all the rules -> records\alerts that i configured in the rules.yaml ?

i was able to configure the alertmanager so i can see my fired alerts, but that is not even close to what im expecting to see like the 'Alerts' or 'Rules' tab that i have in prometheus server.

is there any way to integrate between `rule-evaluator` and `promehteus-server` so i can see all of my rules, or is there any way to watch those unfired Alerts ?

**Comment by lyanco** [comment]
We don't have this... but it's a very good idea. I'll add this towards the top of our backlog - specifically a way to query the rule-evaluator and see what rules are installed and what the current state is, like the /alerts endpoint.

**Comment by DavidMij** [comment]
That will be amazing thank you very much.

**Comment by ImryLevySadan** [comment]
We need it too. This will be great!

**Comment by DavidMij** [comment]
hi @lyanco, any updates?

**Comment by lyanco** [comment]
This isn't expected soon. Will post here when we start working on it.

Note that an analogue - the targets status page - is currently in review at https://github.com/GoogleCloudPlatform/prometheus-engine/pull/301

**Comment by pintohutch** [comment]
Agreed that having a streamlined solution here would be nice. Out of curiosity, what particular info from the [/rules](http://demo.robustperception.io:9090/rules) and [/alerts](http://demo.robustperception.io:9090/alerts) endpoints are of interest?

Note that for pending or firing alerts, Prometheus [creates](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#inspecting-alerts-during-runtime) synthetic time series `ALERTS` that are queryable alongside your regularly-ingested metrics.

**Comment by parkedwards** [comment]
@pintohutch for me, the most helpful info from those page routes is the status of the deployed rules -- we'd want to make sure that rules are correctly registered at the evaluator layer after frequent deploys

**Comment by pintohutch** [comment]
Thanks @parkedwards - that's helpful context. We'll keep this issue open as we iterate.

**Comment by lyanco** [comment]
No movement so far. We've been focusing on delivering a fully-managed, Cloud-based alerting flow (PromQL through Cloud Alerting). This will accept rule_files format and execute them without any infrastructure running in your cluster. It also will have a rich UI to view, edit, and see the status of alerts, which should more fully solve the problems listed here.

Note that the current alerting flow isn't going to be deprecated or anything... we just expect most people to move to the fully cloud-based solution over time as it's more in line with expectations.

If you're interested in joining the preview, you can do so by filling out this form: https://docs.google.com/forms/d/e/1FAIpQLSf7XlkxiDhnlqKDtdJAOwbimGUskEP_Q2V2zqleMCP5m4C_Bg/viewform

**Comment by pandrian** [comment]
Thanks @lyanco I guess in our case we are not using the fully-managed prometheus because we scrape GCE instances. 
would this be supported for self-deployed versions as well?

**Comment by lyanco** [comment]
PromQL in Cloud Alerting should work for all environments and all clouds, yes.

FWIW If you're using self-deployed collection, the /rules and /alerts APIs should be functional on it, but it will only show those rules and alerts that are installed in the local server and executing against local data. It won't show any rules/alerts executing against Monarch, but this might suffice for your use case.

**Comment by pintohutch** [comment]
Hey @pandrian,

Aside from leaning into the Cloud Alerting PromQL preview Lee mentioned, you can manually pull Prometheus metrics from the rule-evaluator's metrics endpoint ([example](https://gist.github.com/pintohutch/4bc09ce40784b8c12b7f4dedb73881d2)) to get better signal of what it's doing with your configured Rules.

This is obviously not as nice as the Prometheus `/rules` API, but evaluating these along with any of its logs can be a helpful sanity check.

**Comment by yama6a** [comment]
Hi there,

We are currently in the process of migrating from a self-hosted prometheus installation to Google Managed Prometheus. Within the scope of that migration, the only way we found that somewhat comes close to listing all rules was to pull and parse the configMap that gets created by the Operator, and that gets then ingested by the rule-evaluator. 

Perhaps it helps someone. It looks something like this:
```bash
kubectl get configmap -n gmp-system rules-generated -o yaml \
| while IFS= read -r line; do echo "---"; echo "$line" \
| sed 's/^[^:]*: //' \
| base64 -d \
| gunzip \
| yq e '.groups[].rules' \
| yq e '.[] \
| [{"alert": .alert, "message": .annotations.message, "summary": .annotations.summary, "expr": .expr}]'; done \
| yq
```

The data is gzipped and base64-encoded in the configmap, with one file per line, hence the long pipe-train. Keep in mind that this is no guarantee that the rule is valid or actually actively being evaluated by the rule-evaluator. It's merely a list of GlobalRules, ClusterRules and Rules resources that were picked up by the gmp operator.

It kinda sorta works. But that being said, it isn't particularly user-friendly or reliable, and we would very much like to be able to add the rule-evaluator as a data-source to Grafana to properly visualize all rules as is possible using a "regular" prometheus setup.

I just forked this repo earlier today and worked on an implementation of the `/api/v1/rules` endpoint, making it compatible with the official prometheus one (see here: https://prometheus.io/docs/prometheus/latest/querying/api/#rules)

Here's an open PR for the endpoint. Would be happy for feedback. Unfortunately I couldn't fully make use of `make presubmit` and `make e2e` - something makes colima explode. 🤷  Please let me know if there's anything missing or not as expected.

https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1149

**Comment by pintohutch** [comment]
Thanks for the contribution @yama6a!

I'm going to close this as #1149 looks like it solved it pretty nicely.
