### ISSUE TITLE
Scraping external HTTP Endpoint with Basic Auth

### ISSUE THREAD

**Issue by naveensrinivasan** [GoogleCloudPlatform/prometheus-engine#298]
We would like examples or instructions on scraping an external endpoint with Basic Auth.

https://www.mongodb.com/docs/atlas/tutorial/prometheus-integration/

**Comment by naveensrinivasan** [comment]
cc @lyanco

**Comment by lyanco** [comment]
I don't believe this is possible with managed collection, as they run as node agents and only scrape endpoints on their own node. As such there's no way to scrape outside the node, and therefore no external endpoint scraping.

You'd have to set up a self-deployed collector to do this (https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-unmanaged) which you could configure to scrape an external endpoint just like a regular Prometheus server.

**Comment by naveensrinivasan** [comment]
> I don't believe this is possible with managed collectors, as they run as node agents and only scrape endpoints on their own node. As such there's no way to scrape outside the node, and therefore no external endpoint scraping.
> 
> You'd have to set up a self-deployed collector to do this (https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-unmanaged) which you could configure to scrape an external endpoint just like a regular Prometheus server.

Thanks, Can we have both? Managed as well as unmanaged?

**Comment by lyanco** [comment]
Yes, you can set both up in the same cluster.
