### ISSUE TITLE
kube-state-metrics do not show up in GMP

### ISSUE THREAD

**Issue by pbnsilva** [GoogleCloudPlatform/prometheus-engine#328]
Hi,

I've set up the kube-state-metrics exporter as shown here: https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters

It's working; if I port-forward to it and check /metrics, there's plenty there.

However, none of these metrics are showing up in GMP.

I've set up node-exporter the same way, and all those are visible in GMP.

How can I start debugging this?

**Comment by pintohutch** [comment]
Hi @pbnsilva,

We're [working](https://github.com/GoogleCloudPlatform/prometheus-engine/pull/301) on surfacing this information better to users.

In the meantime. you can try the following:
```bash
# Get the NODE where KSM pod is deployed.
kubectl get po -lapp.kubernetes.io/name=kube-state-metrics -A -owide
# Find the co-located collector pod name.
kubectl describe node <NODE_NAME> | grep collector
# Port-forward the collector's web UI.
kubectl port-forward <COLLECTOR_POD> -ngmp-system 19090
# In a browser, navigate to http://localhost:19090/targets and check if there are any connection issues.
```

**Comment by pbnsilva** [comment]
Ah, in fact that collector pod is crashing due to authentication issues:

```
ts=2022-09-26T08:57:09.647Z caller=web.go:541 level=info component=web msg="Start listening for connections" address=:19090
ts=2022-09-26T08:57:09.648Z caller=main.go:828 level=error msg="Unable to init Google Cloud Monitoring exporter" err="create metric client: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."
```

**Comment by pintohutch** [comment]
Ah yea - we have [docs](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#gmp-outside-gke) for running managed collection outside of GKE. Let us know how it goes!

Closing.

**Comment by pbnsilva** [comment]
I do have all that set up. Is the collector just meant to get the credentials from the operator?

**Comment by pintohutch** [comment]
Yep
