### ISSUE TITLE
help withe metric drop config

### ISSUE THREAD

**Issue by F5-cheng** [GoogleCloudPlatform/prometheus-engine#347]
Hi, I would like to have some help regarding metric drop config. 

Here is the config I used to drop scrape_duration_seconds metric. 

        static_configs:
          - targets: ["localhost:8080"]
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: '(scrape_duration_seconds|scrape_samples_scraped|scrape_samples_post_metric_relabeling)'
            action: drop

the config seems straightforward, however the metric was not dropped during a test running. Appreciate any help!

**Comment by pintohutch** [comment]
Hi @F5-cheng,

Those metrics are [automatically generated](https://prometheus.io/docs/concepts/jobs_instances/#automatically-generated-labels-and-time-series) by Prometheus at scrape time and [not able to be dropped](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs) using `metric_relabel_configs`. Specifically the docs say:

> Metric relabeling does not apply to automatically generated timeseries such as up.

This is general Prometheus behavior btw as mentioned in https://github.com/prometheus/prometheus/issues/8136.

Closing.

**Comment by F5-cheng** [comment]
Thanks for the info!
