### ISSUE TITLE
no way to set `web.external-url` on Managed Alertmanager

### ISSUE THREAD

**Issue by parkedwards** [GoogleCloudPlatform/prometheus-engine#352]
Hey there! Thanks very much for this project, it's been very simple to set up.

With self-managed Prometheus/Alertmanager, regardless of the helm chart / operator / managed process approach, there's usually a way to set the [`-web.external-url` runtime flag](https://github.com/prometheus/alertmanager/blob/28c3df01739b3e8b5e33004a776db53fd576e7b8/cmd/alertmanager/main.go#L205).  I'm having some challenges [finding a way to inject this with the GMP operator](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/main/manifests/operator.yaml#L906-L911).

Without being able to set this backlink, our Alertmanager notifications won't contain some way for our responders to link back to the AM alert itself, since like many, we're running Alertmanager from inside of a private k8s cluster

**Comment by damemi** [comment]
For managed GMP and the helm chart, this will need an update to be able to pass extra flags. For self-deployed (unmanaged) GMP deployed with `kubectl`, you should be able to modify the yaml directly to add that flag

**Comment by gravelg** [comment]
Currently running into this issue with managed alertmanager, I have to build the URL from another available one. It would be very convenient to be able to set this property to my grafana instance URL.

**Comment by pintohutch** [comment]
Hi @gravelg,

Thanks for commenting here. We should be able to support this with a new cut of the GMP Alertmanager fork. We're putting that together here https://github.com/GoogleCloudPlatform/alertmanager/pull/56. Stay tuned.
