### ISSUE TITLE
When setting --web.external-url I get in a redirect loop

### ISSUE THREAD

**Issue by tljdebrouwer** [GoogleCloudPlatform/prometheus-engine#357]
When ever I set the --web.external-url to anything, I tried things like:
- https://<domain>/prometheus
- https://<domain>/prometheus/
- /prometheus
- /prometheus/

I get in a constant redirect loop

e.g it redirects to /prometheus/graph, and /prometheus/graph redirects to /prometheus/graph again.

When I don't use the --web.external-url the application does work, but ofcourse I would like to host it behind a custom path.

I tried version v0.5.0-gke.0 and v0.4.3-gke.0

Any idea how to get this fixed?

Thanks

**Comment by lyanco** [comment]
See https://github.com/GoogleCloudPlatform/prometheus-engine/issues/352, we'll have to include it in our next release

Is this in Managed Alertmanager as deployed by gcloud and running on GKE?

**Comment by tljdebrouwer** [comment]
It's the frontend.

I followed the step defined here to create the deployment / service: https://cloud.google.com/stackdriver/docs/managed-prometheus/query#ui-prometheus

We run it on GKE autopilot.

**Comment by tljdebrouwer** [comment]
The property is supported https://github.com/GoogleCloudPlatform/prometheus-engine/blob/main/cmd/frontend/main.go#L62

**Comment by pintohutch** [comment]
This seems to be a bug with our redirect handler in the frontend. We'll take a look - thanks for reporting @tljdebrouwer
