### ISSUE TITLE
Cloud Monitoring PromQL metrics have non-string label values + fail regex expressions

### ISSUE THREAD

**Issue by parkedwards** [GoogleCloudPlatform/prometheus-engine#358]
Hello!  We are currently using the managed collection component in GMP.  We are collecting both custom Prometheus counters, as well as [Cloud Monitoring metrics written to Prometheus](https://cloud.google.com/stackdriver/docs/managed-prometheus/promql#transforming-names)

For Cloud Monitoring PromQL metrics, specifically in the `loadbalancing_googleapis` resource namespace, I'm noticing that some label values are "non-string" (they're being read as integers), so the regexp expression fails here.  

My use case is to filter for request-based time series for non 400/500s.  Without being able to use a regex comparison here, we'll have to explicitly exclude every response code in the label expressions

Here are some examples:

Here, we'll just use the regex comparison value on `response_code`
![image](https://user-images.githubusercontent.com/19556538/200054300-e0abe6fe-501c-4741-93fc-2d115ac934c1.png)
```
regex matches are not currently supported on non-string labels
```

Here, we'll actually pass a regex expression:
![image](https://user-images.githubusercontent.com/19556538/200054462-ab33d15c-c8e1-4565-8325-ff4526d07f98.png)
```
 unable to parse value in matcher on int label to an int: strconv.ParseInt: parsing "(4|5).+": invalid syntax
```

Here's an example of a similar (but successful) expression:
![image](https://user-images.githubusercontent.com/19556538/200054710-cdc442bb-0e03-4118-87bb-819a9dd7916c.png)

I'm not sure if this is a bug, intended behavior, or we are missing a configuration

**Comment by pintohutch** [comment]
Hi @parkedwards - this is the same issue as reported in https://github.com/GoogleCloudPlatform/prometheus-engine/issues/299.

I'm going to close this and we can track the feature in the canonical issue at #299.
