### ISSUE TITLE
Most pods in gmp-system stay in Waiting status : CreateContainerConfigError

### ISSUE THREAD

**Issue by Aiesnow** [GoogleCloudPlatform/prometheus-engine#373]
Hello, I'm currently having a problem with managed collection on a private GKE cluster, since today most pods from the gmp-system namespace (mostly collectors) cannot start because of a CreateContainerConfigError on the init container.

I'm seeing events like : 

> MountVolume.SetUp failed for volume "kube-api-access-9qx8d" : object "gmp-system"/"kube-root-ca.crt" not registered
> MountVolume.SetUp failed for volume "config" : object "gmp-system"/"collector" not registered

However those objects exist as I can see them using k9s or kubectl.

When I try to remove a collector pod so that it is recreated by the daemonset, I have a different error that looks more on point : 

> container has runAsNonRoot and image will run as root (pod: "collector-vlwx2_gmp-system(026c0c3e-6047-49cd-9fbe-72352e234127)", container: config-init)

It looks like the initContainer is missing some securityContext definition, what do you think ?

Thanks in advance for you help & support :)

**Comment by Aiesnow** [comment]
Hello, As a follow

**Comment by pintohutch** [comment]
Hi @Aiesnow,

Apologies for the delay in response here. Thanks for reporting - your intuition is indeed correct!

We'll keep this open, but we already have a fix up in #383.

We'll incorporate these changes into the upcoming release.

**Comment by pintohutch** [comment]
Hey @Aiesnow - do you happen to know what component in your cluster was reporting these issues? Was there a specific PodSecurityPolicy in place, for example?

**Comment by pintohutch** [comment]
Yea - I think I've been able to reproduce the error. I enabled the [pod-security-policy](https://cloud.google.com/sdk/gcloud/reference/beta/container/clusters/update#--enable-pod-security-policy) controller on my GKE cluster and deployed a [restricted PSP](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/policy/restricted-psp.yaml) that would capture pods running with the collector's service account.

I then upgraded GMP to latest release and saw the same events as posted here.

For future reference, this can be fixed by patching three resources with the same payload:
```bash
kubectl patch daemonset collector -ngmp-system -p '{"spec":{"template":{"spec":{"initContainers":[{"name":"config-init","securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["all"]},"privileged":false,"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000,"seccompProfile":{"type":"RuntimeDefault"}}}]}}}}'
kubectl patch deployment rule-evaluator -ngmp-system -p '{"spec":{"template":{"spec":{"initContainers":[{"name":"config-init","securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["all"]},"privileged":false,"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000,"seccompProfile":{"type":"RuntimeDefault"}}}]}}}}'
kubectl patch statefulset alertmanager -ngmp-system -p '{"spec":{"template":{"spec":{"initContainers":[{"name":"config-init","securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["all"]},"privileged":false,"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000,"seccompProfile":{"type":"RuntimeDefault"}}}]}}}}'
# alertmanager statefulset pod needs to be kicked for change to take affect.
kubectl delete po -ngmp-system alertmanager-0
```

FYI @lyanco @StevenYCChou @TheSpiritXIII

**Comment by Aiesnow** [comment]
Yes I found the same fix while experimenting on development clusters, so I applied this fix on all our other clusters as well because most of them had the issue (they all have a restricted PSP indeed !). Thanks a lot for the support & quick fix :)
