### ISSUE TITLE
Batch size send deadline exceeded

### ISSUE THREAD

**Issue by savanipoojan78** [GoogleCloudPlatform/prometheus-engine#406]
we are seeing this error logs in the prometheus-engine while pushing metrics to GMP.

```
send batch, rpc error: code = Unavailable desc = Deadline expired before operation could complete.
```
Image we are using is :- `v2.35.0-gmp.2-gke.0`
Now this is an intermediate it happens sometime 
what we wanted to know is when this happen does it have any fallback mechanism or retry or we just lose this batch all together.

One more error we are seeing is 
```
rpc error: code = DeadlineExceeded desc = context deadline exceeded
```  

can you explain a little bit more about this error not sure about this. Both of this error are intermediate,

**Comment by savanipoojan78** [comment]
We encountered this error again in of the region `us-east4`

If you look at this chart we did see a spike in error rate 
<img width="1788" alt="Screenshot 2022-12-27 at 9 21 32 PM" src="https://user-images.githubusercontent.com/33199323/209690101-3942c949-b0f8-4b8c-b23e-56a273fd96ed.png">

<img width="1911" alt="Screenshot 2022-12-27 at 9 22 32 PM" src="https://user-images.githubusercontent.com/33199323/209690469-0d9b3af1-60a7-4703-b965-bf3eb6f21897.png">


After i restarted the prometheus statefulset it got resolved

**Comment by savanipoojan78** [comment]
@pintohutch Any Update on this issue ?

**Comment by pintohutch** [comment]
Hi @savanipoojan78,

Apologies for the delayed response. The 5xx's are typically a result of service degradation of Google Cloud Monitoring (GCM). It's possible you were seeing this as a result of [this incident](https://status.cloud.google.com/incidents/HdrPC498EDhPMm1DCDhT) in December. You should be seeing consistent success when writing to GCM as that issue has been resolved.

> what we wanted to know is when this happen does it have any fallback mechanism or retry or we just lose this batch all together.

We explicitly [do not retry](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.6.0-rc.0/pkg/export/export.go#L820-L821) if there are problems writing to GCM to avoid HOL blocking. The idea here being: it's presumably more valuable to have monitoring on the _latest_ data than _historical_ or "backfilled" data for critical applications.

Hope that helps.

**Comment by savanipoojan78** [comment]
Thank you @pintohutch For the response but this happen today as well
What we have seen is from past 28 days data we are seeing this for us-east4 region very frequently 
and also what we have observer is when we restart the stateful-set its resolved ,after the restart we don't see the above error in the prometheus pod logs 

16 Jan'23 from from 9AM-10AM UTC we were seeing this issue 

<img width="1887" alt="Screenshot 2023-01-16 at 4 51 51 PM" src="https://user-images.githubusercontent.com/33199323/212667045-fe1b864b-1031-419c-89d5-cd9ba7981620.png">

**Comment by pintohutch** [comment]
Hey @savanipoojan78,

It's possible you may be sending samples too frequently to the backend. What's your `scrape_interval` set to?

Managed Service for Prometheus supports a minimum interval of [5s](https://cloud.google.com/stackdriver/docs/managed-prometheus#gmp-data-storage).

**Comment by pintohutch** [comment]
Or another possibility: are you running multiple Prometheus binaries, each writing to the same time series in the backend which could be causing this?

**Comment by savanipoojan78** [comment]
1. we are setting scrape_interval as 60s for all the prometheus job
2. Yes , we are sending metrics from different region in same TS but different labels values (ex cluster_name and location will be different) could this be problem in future as we increase the number of worker to monitor in each region? which will send the data to same TS? do you have any suggestion? why we wanted to do that is because we wanted to have an consolidated view of our system.

**Comment by pintohutch** [comment]
1. Gotcha - 60s should be fine.
2. Cool - there's no problem with that pattern. However, you should ensure that you are setting the `cluster` label for each deployment, and that it's set differently, depending on where it's deployed. Otherwise, you could be writing colliding data to the same time series.

You can set this either in your Prometheus configuration [`external_labels`](https://github.com/prometheus/prometheus/blob/release-2.41/config/testdata/conf.good.yml#L7) or via a [flag](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/c5b2885baad4ec209a4f9a8c6dab722692c21dd7/pkg/export/setup/setup.go#L143-L144) passed to your Prometheus binary.

**Comment by pintohutch** [comment]
Also note, if you have more than one Prometheus deployment per `cluster`, you can further distinguish colliding timeseries through the `namespace` label. This is most relevant for K8s deployments, however you may have some analogous notion of `namespace` in your environment (e.g. logical network isolation within your `cluster`).

You can provide this in your [`external_labels`](https://github.com/prometheus/prometheus/blob/release-2.41/config/testdata/conf.good.yml#L7) config as well.

**Comment by savanipoojan78** [comment]
we are following above things that you mention.

**Comment by pintohutch** [comment]
The colliding time series that I'm able to see are missing the `cluster` and `namespace` labels.

**Comment by pintohutch** [comment]
Resolved through the support case.
