### ISSUE TITLE
optional store exporting data (export.match)

### ISSUE THREAD

**Issue by prudnitskiy** [GoogleCloudPlatform/prometheus-engine#407]
Current Prometheus engine implementation exports data matched to the GSD. Data not matching the `export.match` specification is stored locally. It would be great if there will be an option to store _all_ data (including data exported).

Please point me to the docs if this option already exists but I've missed it.

**Comment by pintohutch** [comment]
Hi @prudnitskiy,

All data should already be stored in the local Prometheus server for its configured `--storage.tsdb.retention.time`.

For managed-collection, we limit this to [30m](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.5.0/cmd/operator/deploy/operator/10-collector.yaml#L52-L55) to constrain memory usage, so if you're checking after that, you wouldn't see the data there.

If you're interested in retaining the data for longer, feel free to customize the install manifests your self to retain all data for longer (either for [self-deployed](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.5.0/examples/prometheus.yaml#L85) or [managed-collection](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.5.0/manifests/operator.yaml#L531)).

**Comment by pintohutch** [comment]
Closing. If there are any other questions or discrepancies, please re-open and reach out.
