### ISSUE TITLE
arm64 support as it is now possible to create a arm64 node pool on GKE

### ISSUE THREAD

**Issue by k4leung4** [GoogleCloudPlatform/prometheus-engine#409]
arm64 support as it is now possible to create a arm64 node pool on GKE

from what I can tell, all the images for GMP are amd64 arch type only.
would love to see support for arm64 so when I run an arm64 GKE cluster, GMP doesn't fail to run.

**Comment by pintohutch** [comment]
Hi @k4leung4,

Yes! We will have an update on this and will keep this issue open for tracking.

**Comment by pintohutch** [comment]
Closing this as a duplicate of #166
