### ISSUE TITLE
Update golang.org/x/oauth2

### ISSUE THREAD

**Issue by gfrankliu** [GoogleCloudPlatform/prometheus-engine#434]
Can we bump up golang.org/x/oauth2 version?
The one here is old and doesn't support "executable.command" in the external account credentials file, as documented in https://google.aip.dev/auth/4117

**Comment by gfrankliu** [comment]
Confirmed latest (v0.5.0 from 2/8/2023) from https://pkg.go.dev/golang.org/x/oauth2/google supports "executable.command" in the external account credentials file.

**Comment by gfrankliu** [comment]
Any updates? I see the PR#437 sitting in Draft for a few months.

**Comment by pintohutch** [comment]
Whoops - thanks for pinging here. I've promoted it to a formal PR and it's in review!
