### ISSUE TITLE
Rate is not working for gauge metrics

### ISSUE THREAD

**Issue by eat-code-sleep-000** [GoogleCloudPlatform/prometheus-engine#436]
- This promql metric: **rate(kafka_topic_partition_current_offset[5m])** is not working when executed with Metric explorer PromQL tab.
- There is also no option such as rate or delta to the Post Processing on Configuration tab. Is this a limitation on gauge metrics?
- The same query is working fine with Prometheus UI and Grafana

**Comment by lyanco** [comment]
Can you please send more details to (my Github username) at (the company I work for) .com? Need things like your project ID to investigate. Also, can you confirm your UI and Grafana are pointing at the frontend proxy instead of your local prometheus?

**Comment by eat-code17** [comment]
Hi @lyanco, 

- I am using a corporate email so I'm not sure if I can provide those details. 
- Regarding where Prom UI and Grafana is pointed, it is pointed to the Kafka Exporter Deployment in GKE and not in Local. Prom UI and Grafana is also deployed on GKE
- Executing just this query **kafka_topic_partition_current_offset** returns result but adding the rate function doesn't return any data.
- When rate function is used in counter metrics (Sample: rate(http_requests_total[5m])), it returns values
