### ISSUE TITLE
Collectors managing to export to GMP after Workload Identity enabled

### ISSUE THREAD

**Issue by nick-jones** [GoogleCloudPlatform/prometheus-engine#443]
..that may sound like a good thing (i.e. nothing broke), but I'm confused as to why this was the case.

Context:
- Workload Identity is enabled on the GKE cluster
- GKE Metadata Server is enabled on _all node pools_
- Using managed collection (not self-deployed)
- Collectors have been restarted at some point after the GKE Metadata Servers came into play
- Not using Autopilot

The [documentation](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed) states:

> When running on GKE, the collecting Prometheus server automatically retrieves credentials from the environment based on the Compute Engine default service account or the Workload Identity setup.

Best I can tell, the collectors are continuing to use the "Compute Engine default service account" (I can prove this by revoking access to write metrics for that SA temporarily). I was fully expecting to have to setup a new Google Cloud SA with the relevant perms and annotate the `collector` kubernetes SA.

Testing in namespaces other than `gmp-system`, access to GCP resources does appear to be restricted, as expected.

Is the documentation mildly misleading here? Or have I potentially misconfigured something?

**Comment by lyanco** [comment]
This is WAI - the node SAs by default have monitoring.writer perms so they can send free GKE metrics without you having to configure anything. We piggyback on that permission when using managed collection on GKE. This is why the WI instructions are not replicated on that page.

The reference to WI is likely there because it's a shared section. I can update it.

**Comment by nick-jones** [comment]
Many thanks for the explanation.

Am I correct in my understanding then, that this piggybacking behaviour is bespoke to the `gmp-system` namespace when Workload Identity is enabled and the GKE Metadata Servers are in play? It does appear that way to me:

*gmp-system* namespace

```
$ kubectl --namespace=gmp-system debug -it collector-f8vf5 --image=alpine:latest --target=prometheus 
Targeting container "prometheus". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
Defaulting debug container name to debugger-txt9q.
If you don't see a command prompt, try pressing enter.
/ # apk add jq curl
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
<snip>
/ # curl -s -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token > /tmp/token.json
/ # curl -s -H "Authorization: Bearer $(cat /tmp/token.json | jq '.access_token')" "https://monitoring.googleapis.com/v3/projects/***/groups"
{}
```

*test* namespace (this pod does not specify any k8s SA, and the default k8s SA does not have any annotations associating it with a Google Cloud SA)

```
$ kubectl --namespace=test debug -it traefik-7999769574-4jkn2 --image=alpine:latest --target=traefik
Targeting container "traefik". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
Defaulting debug container name to debugger-2xzn5.
If you don't see a command prompt, try pressing enter.
/ # apk add jq curl
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
<snip>
/ # curl -s -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token > /tmp/token.json
/ # curl -s -H "Authorization: Bearer $(cat /tmp/token.json | jq '.access_token')" "https://monitoring.googleapis.com/v3/projects/***/groups"
{
  "error": {
    "code": 403,
    "message": "Permission denied (or the resource may not exist).",
    "status": "PERMISSION_DENIED"
  }
}
```

**Comment by lyanco** [comment]
Yes, the gmp-system namespace is created with those permissions bound, hence we don't recommend changing it or putting anything else in it. In fact, you can't even touch it on Autopilot clusters.

**Comment by nick-jones** [comment]
Thanks, that makes sense. I'm closing this then, as there was no underlying issue here - and it looks like the documentation was updated too :-)
