### ISSUE TITLE
Protected scrape endpoints

### ISSUE THREAD

**Issue by TheSpiritXIII** [GoogleCloudPlatform/prometheus-engine#450]
Support mTLS, OAuth2, Authorization and BasicAuth on the PodMonitoring ScrapeEndpoint level.

**Comment by pinkfish** [comment]
Is there a way to solve this?  Just ran into this issue myself :(

**Comment by AgustinRamiroDiaz** [comment]
https://github.com/GoogleCloudPlatform/prometheus-engine/pull/652 is awesome! Is there an estimate on when will it be available in GMP?

**Comment by AgustinRamiroDiaz** [comment]
https://github.com/GoogleCloudPlatform/prometheus-engine/issues/241 is a subset of this one
