### ISSUE TITLE
No endpointStatuses present

### ISSUE THREAD

**Issue by a-candiotti-pvotal** [GoogleCloudPlatform/prometheus-engine#455]
When i'm doing a kubectl describe to get the status of the clusterPodMonitoring or podMonitoring objects, no "endpointStatuses" objects are present, making it difficult to debug.

I'd be happy to provide more informations on my environment.

**Comment by a-candiotti-pvotal** [comment]
I deployed prometheus managed version through the UI.
i'm not sure how to get the version sorry.

Where can I get this information please?

**Comment by TeChn4K** [comment]
Same issue as @a-candiotti-pvotal : no endpointStatuses at all on my describes

My GKE cluster is running on 1.26.5-gke.1200

Is there any version (regular or preview) with this feature available?

**Comment by macxamin** [comment]
Hello guys, I just tried this and it works for me on 1.26.5-gke.1200
![image](https://github.com/GoogleCloudPlatform/prometheus-engine/assets/89922129/ada1e530-98bb-4c95-9a33-bd595e8059b7)

Your issue could be happening for two reasons:

1. You did not enable target status feature. Follow the instructions [here](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#target-status). You can use `kubectl -n gmp-public edit operatorconfig config` to check if you have it enabled.
2. You don't have an app up and running that you can target. You can [follow the example app instructions](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#deploy-app) to deploy it.

Do steps 1 and 2 and let me know if it works.
