### ISSUE TITLE
prometheus-frontend taking 20-30s to initially load

### ISSUE THREAD

**Issue by parkedwards** [GoogleCloudPlatform/prometheus-engine#460]
hey there,

we've been using GMP + Grafana for a few months now

recently, we've started to experience some inexplicable latency, starting with our prometheus-frontend deployment (we use this for the Query Browser, but also for Grafana to query internally within the cluster)

for context, we are running this version:
```
gke.gcr.io/prometheus-engine/frontend:v0.5.0-gke.0
```

when i inspect one such slow load, this is what we see:

![image](https://user-images.githubusercontent.com/19556538/232572735-730f3a0f-ca2f-4270-b42c-c44b32c2a046.png)

as you can see, the JS bundle as well as the ready checks are taking very long.  

additionally, our self-hosted Grafana deployment talks to the prometheus-frontend inside of our cluster (they live in the same namespace).  we've started to notice some excessive query times there, though we're trying to rule out the Grafana deployment itself as an issue

im trying to understand what some possible culprits might be.  could you advise?

**Comment by parkedwards** [comment]
oh also worth mentioning - the prometheus-frontend deployment does spit out some error logs around failing to talk to GCM bc of `context canceled`.  however, im not seeing a significant increase in such cases when we plot this out over time -- the latencies we're experiencing, however, started cropping up in the last week or so

```
equesting GCM failed" err="Get \"https://monitoring.googleapis.com/v1/projects/<gcp-project>/location/global/prometheus/api/v1/query_range?end=1681753980&query=sum+by+%28database%29+%28increase%28cloudsql_googleapis_com%3Adatabase_postgresql_deadlock_count<some-query-params>&step=60\": context canceled"
```

**Comment by macxamin** [comment]
When are you seeing the js load and ready? If it is on startup? GMP is only relevant when querying. GMP also doesn't have a endpoint named `ready`. 

As for:
```
requesting GCM failed" err="Get \"https://monitoring.googleapis.com/v1/projects/<gcp-project>/location/global/prometheus/api/v1/query_range?end=1681753980&query=sum+by+%28database%29+%28increase%28cloudsql_googleapis_com%3Adatabase_postgresql_deadlock_count<some-query-params>&step=60\": context canceled"
```

This could mean a timeout was hit because the query took too long. I would run the same query in the Cloud console and see how long it takes and compare to your timeout. If it's similar we can try investigating further.
