### ISSUE TITLE
TLS certificate not valid for googleapis.com

### ISSUE THREAD

**Issue by QuerQue** [GoogleCloudPlatform/prometheus-engine#470]
Hi,
I try to set up managed collection for non-GKE Kubernetes clusters. I follow instruction https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#enable-mgdcoll-non-gke
Unfortunately seems like there is some problem with TLS authentication.
Collector pod prints 
`"transport: authentication handshake failed: x509: certificate is valid for ....., not monitoring.googleapis.com\""`
Rule-evaluator prins
Error querying Prometheus: Post `\"https://monitoring.googleapis.com/v1/projects/<project>/location/global/prometheus/api/v1/query\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": x509: certificate is valid for ...., not oauth2.googleapis.com"`

Can I disable tls verification? Or maybe how can I add tls cert valid for googleapis.com? 
Any tip will be helpful.

**Comment by pintohutch** [comment]
We should update the docs to make this more clear, but have you tried specifying your GCP SA credentials as mentioned in https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#gmp-outside-gke?

**Comment by pintohutch** [comment]
Ahh good to know. Thanks for posting. Going to mark this as closed.
