### ISSUE TITLE
[Feature Request] Support log json format

### ISSUE THREAD

**Issue by govargo** [GoogleCloudPlatform/prometheus-engine#629]
Currently, majority of components(frontend, rule-evaluator, operator, config-reloader) don't support log format flag.

These components write logs to stderr.
So if the users deploy on GKE, the Cloud Logging routes to the ERROR logs even if it is info logs.
The logs of these components are routed as a textPayload, not structed log.
<img width="1375" alt="スクリーンショット 2023-10-15 13 27 15" src="https://github.com/GoogleCloudPlatform/prometheus-engine/assets/44902466/dbaf6900-c22c-43d9-9034-e5179d85f1ed">

Promtheus itself supports `--log. format`. If the user specifies `--log.format=json`, the Cloud Logging can classify that it is the struct log.
<img width="1071" alt="スクリーンショット 2023-10-15 16 24 04" src="https://github.com/GoogleCloudPlatform/prometheus-engine/assets/44902466/cef94868-aa9f-447d-b5fd-f897ab658eff">

<img width="1357" alt="スクリーンショット 2023-10-15 16 25 50" src="https://github.com/GoogleCloudPlatform/prometheus-engine/assets/44902466/10f218a6-d041-4ceb-91f9-e3bf251c9419">

I hope frontend, rule-evaluator, operator, config-reloader can support log format json by command args, such like Prometheus.

**Comment by pintohutch** [comment]
cc @macxamin

**Comment by govargo** [comment]
Hi

Thank you!
I missed #522 PR.

It would be great and my issue will be resolve.
I'll check at release v0.7.4.

Thank you.
