### ISSUE TITLE
make docker builds multi-platform

### ISSUE THREAD

**Issue by bwplotka** [GoogleCloudPlatform/prometheus-engine#710]
AC:
* Running make <command> <target> will build docker image for desired platform

This way we can build amd64 images from arm (for example).

**Comment by TheSpiritXIII** [comment]
`docker buildx` allows you to do this already using e.g. `--platform linux/arm64`.

**Comment by pintohutch** [comment]
This is already possible today, see https://github.com/GoogleCloudPlatform/prometheus-engine/blob/main/Makefile#L88
