### ISSUE TITLE
Managed Service for Prometheus Release Schedule and Release Notes

### ISSUE THREAD

**Issue by tp-fp** [GoogleCloudPlatform/prometheus-engine#775]
Hi, I'd like to see if there is an up-to-date documentation page where we can find the release notes for each version that is released for the managed prometheus version and what the release schedule is for new releases.

I tried looking in the following locations but did not yield any good results:
- [Github Releases](https://github.com/GoogleCloudPlatform/prometheus-engine/releases)
  - This seems to be sparsely updated as the latest is showing `0.7.4` but looking at are configuration in GKE we are on `0.8.0`.
- [Google Cloud Docs](https://cloud.google.com/stackdriver/docs/managed-prometheus)
  - No page I could find there for release notes or schedule
 - [GKE Release Notes](https://cloud.google.com/kubernetes-engine/docs/release-notes#no-channel)
   - I was curious if they would perhaps be lumped in here but did not find anything when searching through
 - [Container Registry](https://console.cloud.google.com/gcr/images/gke-release/global/prometheus-engine/operator)
   - The best I could find is potentially just looking at the registry. I noticed there are also `0.8.1` and `0.9.0` tagged images in there so potentially those are newer releases? If so, would be interested to know when these get pushed out to clusters and the release notes for them. (_Update_ - Looking at the [tags](https://github.com/GoogleCloudPlatform/prometheus-engine/tags) these seem to just be release candidates at this time)

Hopefully I didn't miss an obvious link somewhere but if so, apologies in advance and thanks for any assistance in this.

**Comment by bernot-dev** [comment]
We currently do not have much information available publicly about our release cycles or change logs. We are in the process of making a series of internal improvements to our processes that will allow for a more consistent release schedule and better visibility for changes. We hope to publish our release schedule by the end of March.

Right now, the best resource for seeing changes is the Git history of our open source repositories. Improvements over the coming months will likely allow us to publish more comprehensive release notes.

The system that pushes release out to GKE clusters using managed collection is quite complex, but most clusters are currently using a 0.8.X version. The rollout process is deliberately gradual to ensure we have the opportunity to detect and respond to potential bugs before large numbers of customers are impacted. You can inspect the various Kubernetes images that are deployed in your cluster to locate the image versions that they are using.

In the meantime, let us know if you have other more specific questions and we will try to address them.

**Comment by tp-fp** [comment]
Awesome, thanks for the quick response!
