### ISSUE TITLE
Add a helm chart for google managed prometheus

### ISSUE THREAD

**Issue by mugioka** [GoogleCloudPlatform/prometheus-engine#90]
Hi, team

Google Managed Prometheus is a very good software.

It would be nice if Google Managed Prometheus could be installed as a helm chart, are there any plans to support this?

**Comment by fabxc** [comment]
We've no immediate plans for a Helm chart. The regular installation path currently does not generally require configuration that could be abstracted into a chart as those configuration values are part of the OperatorConfig CRD.

This may change in the future as the operator evolves. It still remain that Helm charts are just on of several options (Helm, kustomize, cue) to support and we haven't put much thought into it which ones we'd want to provide something official for.

Do you have something particular in mind you'd like to make confiugrable via Helm?

**Comment by mugioka** [comment]
The reason why I wanted to use helm was that it is easy to follow the parameter changes due to application upgrades, and the yaml to be managed is only the values file when installed with helm, which is also attractive.

**Comment by parberge** [comment]
I would like this as well. We use ArgoCD for deployments, and pointing to an external helm chart makes the operation of this much easier.

**Comment by iamolegga** [comment]
Same here, in our case it would be more convenient to ship this with a helm chart by just checking the version of new releases. Currently, as we use terraform for IaaC we should watch the changes in this repo and copypasting text to `.tf` files.

**Comment by pintohutch** [comment]
Hey all,

We've decided to hold off on helm support for the time being, with the reasons mentioned [on #105](https://github.com/GoogleCloudPlatform/prometheus-engine/pull/105#issuecomment-1087862749).
