### ISSUE TITLE
question: liveness and readiness probes for config-reloader

### ISSUE THREAD

**Issue by nvictor** [GoogleCloudPlatform/prometheus-engine#921]
Hello,

I am trying to add liveness and readiness probes to my deployment of `config-reloader` and have a few questions.

The version of `config-reloader` I am using (`0.4.3-gke.0`) doesn't have the `ready-url` flag. That flag was added in a later version. Does `ready-url` specify the readiness endpoint for `config-reloader`?

That brings me to the second question. I don't quite see an endpoint for liveness. What approach would you recommend for implementing liveness for `config-reloader`?

Thank you

**Comment by maxamins** [comment]
`ready-url` specifies if the Prometheus instance the `config-reloader` is watching is ready. Check https://prometheus.io/docs/prometheus/latest/management_api/ fore more info.

> That brings me to the second question. I don't quite see an endpoint for liveness. What approach would you recommend for implementing liveness for config-reloader?

We don't have a ready endpoint for config-reloader. A workaround is you can check and see if [`/metrics`](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/75d445d868e07889b1be1f3555820ce8fcf45729/cmd/config-reloader/main.go#L42) is returning data. 

Why are you trying to add liveness and readiness probes?

**Comment by nvictor** [comment]
Thank you so much for the fast response and for explaining.

To answer your question, `config-reloader` came up after rerunning a check on our cluster to see deployments without liveness or readiness probes.

I will set both probes to the `/metrics` endpoint for now. What do you think?

**Comment by maxamins** [comment]
I would set the probers to the Prometheus readiness/healthy endpoints, since that's what you care about. The `/metrics` endpoint would just be a hacky workaround.

**Comment by nvictor** [comment]
Got it. Thanks

Closing this as well.
